export enum persistKey {
  THEME = "THEME",
  SELECTED_SYMBOL = "SELECTED_SYMBOL",
  BASE_CURRENCY = "BASE_CURRENCY",
  AUTHENTICATION = "AUTHENTICATION",
  VISIBLE_CONTENT = "VISIBLE_CONTENT",
  TWO_FACTOR = "TWO_FACTOR",
  ADDRESSWARNING = "ADDRESSWARNING",
  LANGUAGE = "LANGUAGE",
  FAVORITE_PAIRS = "FAVORITE_PAIRS",
}
