export enum CookiePersistKey {
  hapiAddress = "HAPI_ADDRESS",
  streamAddress = "STREAM_ADDRESS",
  interval = "INTERVAL",
  customUniqData = "CUSTOMUNIQDATA",
  THEME = "THEME",
  BASE_CURRENCY = "BASE_CURRENCY",
  AUTHENTICATION = "AUTHENTICATION",
  VISIBLE_CONTENT = "VISIBLE_CONTENT",
  TWO_FACTOR = "TWO_FACTOR",
  ADDRESSWARNING = "ADDRESSWARNING",
  FAVORITE_PAIRS = "FAVORITE_PAIRS",
}
