export enum ConvertErrorEnums {
  REQUIRED = "REQUIRED",
  INVALID_VALUE = "INVALID_VALUE",
  INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
  INSUFFICIENT_BALANCE_FUND = "INSUFFICIENT_BALANCE_FUND",
  PRICE_LESS_THAN_MIN_PRICE = "PRICE_LESS_THAN_MIN_PRICE",
  PRICE_MORE_THAN_MAX_PRICE = "PRICE_MORE_THAN_MAX_PRICE",
  AMOUNT_MORE_THAN_MAX_PRICE = "AMOUNT_MORE_THAN_MAX_PRICE",
  AMOUNT_LESS_THAN_MIN_PRICE = "AMOUNT_LESS_THAN_MIN_PRICE",
}
